terminate called after throwing an instance of 'std::runtime_error'
  what():  main type should be int
