terminate called after throwing an instance of 'std::runtime_error'
  what():  identifier not defined
